logLevel = "warn"

[install]
linker = "isolated"
registry = "https://registry.npmjs.org"

[test]
coverage = true
coverageThreshold = { line = 0.65, function = 0.8, statement = 0.9 }
coverageReporter = ["lcov", "text"]
