logLevel = "warn"

[install]
  registry = "https://registry.npmjs.org"

[test]
  coverage          = true
  coverageReporter  = ["lcov", "text"]
  coverageThreshold = { line = 0.65, function = 0.8, statement = 0.9 }
