name: Build
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        - name: Set up Tools
          uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2
          with:
            install: true
            cache: true
        - name: Install dependencies
          run: pnpm install --ignore-scripts
