name: Build
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        - name: Set up Tools
          uses: jdx/mise-action@c1606014a9b1b7cd3e7c7f5fc607a25351fdffec # v2
          with:
            install: true
            cache: true
        - name: Install dependencies
          run: pnpm install --ignore-scripts
