name: Build
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v2
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18.x'
            cache: 'yarn'
        - uses: borales/actions-yarn@v3.0.0
          with:
            cmd: install # will run `yarn install` command
        - uses: borales/actions-yarn@v3.0.0
          with:
            cmd: test # will run `yarn test` command
